spring:
  profiles:
    active: local
  config:
    import: "optional:configserver:http://52.79.224.196:8888"
  cloud:
    config:
      name: config

management:
  endpoints:
    web:
      exposure:
        include: refresh

