spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


jasypt:
  encryptor:
    bean: jasyptStringEncryptor
